#!/usr/bin/env node

/* eslint-disable no-unused-expressions, jsdoc/require-jsdoc */

const { join } = require('path');

const yargs = require('yargs');

const raw_gtfs_into_sqlite = require('./src/pipeline_transforms/raw_gtfs_into_sqlite/yargs_wrapper');
const gtfs_as_geojson = require('./src/pipeline_transforms/gtfs_as_geojson/yargs_wrapper');
const gtfs_network = require('./src/pipeline_transforms/gtfs_network/yargs_wrapper');

function addOutputDirToEnvironment(argv) {
  const { output_dir } = argv;
  process.env.AVL_GTFS_CONFLATION_OUTPUT_DIR = output_dir;
  return argv;
}

yargs
  .middleware(addOutputDirToEnvironment)
  .parserConfiguration({
    'camel-case-expansion': false,
    'flatten-duplicate-arrays': false
  })
  .option({
    output_dir: {
      type: 'string',
      desc:
        'Path to the output directory. (Can be set using ENV variable AVL_GTFS_CONFLATION_OUTPUT_DIR.)',
      default:
        process.env.AVL_GTFS_CONFLATION_OUTPUT_DIR ||
        join(process.cwd(), 'output')
    }
  })
  .command(raw_gtfs_into_sqlite)
  .command(gtfs_as_geojson)
  .command(gtfs_network)
  .demandCommand()
  .recommendCommands()
  .strict()
  .wrap(yargs.terminalWidth() / 1.618).argv;
